export const RESTART_ON_REMOUNT = '@@saga-injector/restart-on-remount';
export const DAEMON = '@@saga-injector/daemon';
export const ONCE_TILL_UNMOUNT = '@@saga-injector/once-till-unmount';

// Actions

export const LOAD_USERINFO = 'LOAD_USERINFO';
export const LOAD_USERINFO_SUCCESS = 'LOAD_USERINFO_SUCCESS';
export const LOAD_USERINFO_ERROR = 'LOAD_USERINFO_ERROR';

export const LOAD_USER_ACTIVITY = 'LOAD_USER_ACTIVITY';
export const LOAD_USER_ACTIVITY_SUCCESS = 'LOAD_USER_ACTIVITY_SUCCESS';
export const LOAD_USER_ACTIVITY_ERROR = 'LOAD_USER_ACTIVITY_ERROR';

export const SET_SYMBOL_ID = 'SET_SYMBOL_ID';

export const LOAD_TICKERS_AND_INFO = 'LOAD_TICKERS_AND_INFO';
export const LOAD_TICKERS_AND_INFO_SUCCESS = 'LOAD_TICKERS_AND_INFO_SUCCESS';

export const LOAD_PRICES_SUCCESS = 'LOAD_PRICES_SUCCESS';

export const LOAD_REPOS = 'LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'LOAD_REPOS_ERROR';

export const LOAD_OPEN_TRADES = 'LOAD_OPEN_TRADES';
export const LOAD_OPEN_TRADES_SUCCESS = 'LOAD_OPEN_TRADES_SUCCESS';

export const LOAD_LAST_PRICES = 'LOAD_LAST_PRICES';
export const LOAD_LAST_PRICES_SUCCESS = 'LOAD_LAST_PRICES_SUCCESS';

export const LOAD_CLOSED_TRADES = 'LOAD_CLOSED_TRADES';
export const LOAD_CLOSED_TRADES_SUCCESS = 'LOAD_CLOSED_TRADES_SUCCESS';

export const LOAD_CHART_DATA = 'LOAD_CHART_DATA';
export const LOAD_CHART_DATA_SUCCESS = 'LOAD_CHART_DATA_SUCCESS';

export const SET_UNREAD_NOTIFICATIONS = 'SET_UNREAD_NOTIFICATIONS';
export const SET_SOMETHING_WENT_WRONG = 'SET_SOMETHING_WENT_WRONG';

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
